#@ load("@ytt:data", "data")
#@ load("config.lib.yaml", "labels", "secretCaName")

apiVersion: v1
kind: Secret
metadata:
  labels: #@ labels()
  name: #@ secretCaName()
  namespace: #@ data.values.release.namespace
data:
