#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("config.lib.yaml", "secretTlsName", "secretCaName", "fullName")

#@ def config_yml():
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:

- path: [data]
  type: copy
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: #@ data.values.release.namespace
      name: #@ secretTlsName()
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: #@ data.values.release.namespace
      name: #@ secretCaName()

- path: [webhooks, {allIndexes: true}, clientConfig, caBundle]
  type: copy
  sources: [existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: MutatingWebhookConfiguration}
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: ValidatingWebhookConfiguration}

- path: [spec, conversion, webhook, clientConfig, caBundle]
  type: copy
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: CustomResourceDefinition
      name: tenants.capsule.clastix.io
#@ end

apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ fullName() + "-kapp-config"
  namespace: #@ data.values.release.namespace
  labels:
    kapp.k14s.io/config: ""
data:
  config.yml: #@ yaml.encode(config_yml())