#@ load("@ytt:data", "data")
#@ load("config.lib.yaml", "labels")

apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: default
  labels: #@ labels()
spec:
  forceTenantPrefix: #@ data.values.manager.options.forceTenantPrefix
  userGroups:
  #@ for/end item in data.values.manager.options.capsuleUserGroups:
  - #@ item
  protectedNamespaceRegex: #@ data.values.manager.options.protectedNamespaceRegex
  #!allowTenantIngressHostnamesCollision: #@ data.values.manager.options.allowTenantIngressHostnamesCollision
  #!allowIngressHostnameCollision: #@ data.values.manager.options.allowIngressHostnameCollision
