#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels")

#@ if data.values.serviceMonitor.enabled:
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: #@ labels()
  #@ if data.values.serviceMonitor.labels:
  #@   data.values.serviceMonitor.labels
  #@ end
  name: #@ fullName() + "-metrics-role"
  namespace: #@ data.values.serviceMonitor.namespace if data.values.serviceMonitor.namespace else data.values.release.namespace
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: #@ labels()
  #@ if data.values.serviceMonitor.labels:
  #@   data.values.serviceMonitor.labels
  #@ end
  name: #@ fullName() + "-metrics-rolebinding"
  namespace: #@ data.values.serviceMonitor.namespace if data.values.serviceMonitor.namespace else data.values.release.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: #@ fullName() + "-metrics-role"
subjects:
- kind: ServiceAccount
  name: #@ data.values.serviceMonitor.serviceAccount.name
  namespace: #@ data.values.serviceMonitor.serviceAccount.namespace if data.values.serviceMonitor.serviceAccount.namespace else data.values.release.namespace
#@ end
