#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels")

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: #@ fullName() + "-mutating-webhook-configuration"
  labels: #@ labels()
webhooks:
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: #@ fullName() + "-webhook-service"
      namespace: #@ data.values.release.namespace
      path: /namespace-owner-reference
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: owner.namespace.capsule.clastix.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - namespaces
      scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: #@ data.values.validatingWebhooksTimeoutSeconds
