#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels", "serviceAccountName")

#@ if data.values.serviceAccount.create:
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ serviceAccountName()
  labels: #@ labels()
  #@ if data.values.serviceAccount.annotations:
  annotations: #@ data.values.serviceAccount.annotations
  #@ end
#@ end
