#@data/values
---
#! Default values for capsule.
#! This is a YAML-formatted file.
#! Declare variables to be passed into your templates.

release:
  name: capsule
  service: kapp
  namespace: capsule-system
chart:
  name: capsule
  appVersion: 0.0.5
  version: 0.0.19
manager:
  image:
    repository: quay.io/clastix/capsule
    pullPolicy: IfNotPresent
    tag: ''
  #! Specifies if the container should be started in hostNetwork mode.
  #!
  #! Required for use in some managed kubernetes clusters (such as AWS EKS) with custom
  #! CNI (such as calico), because control-plane managed by AWS cannot communicate
  #! with pods' IP CIDR and admission webhooks are not working
  hostNetwork: false

  #! Additional Capsule options
  options:
    logLevel: '4'
    forceTenantPrefix: false
    capsuleUserGroups: ["capsule.clastix.io"]
    protectedNamespaceRegex: ""
    allowIngressHostnameCollision: true
    allowTenantIngressHostnamesCollision: false
  livenessProbe:
    httpGet:
      path: /healthz
      port: 10080
  readinessProbe:
    httpGet:
      path: /readyz
      port: 10080

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
jobs:
  image:
    repository: quay.io/clastix/kubectl
    pullPolicy: IfNotPresent
    tag: "v1.20.7"
proxy:
  image:
    repository: ""
    pullPolicy: ""
    tag: ""
    
mutatingWebhooksTimeoutSeconds: 30
validatingWebhooksTimeoutSeconds: 30
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: "capsule"
podAnnotations: {}
priorityClassName: ''
nodeSelector: {}
#!  node-role.kubernetes.io/master: ""
tolerations: []
#!- key: CriticalAddonsOnly
#!  operator: Exists
#!- effect: NoSchedule
#!  key: node-role.kubernetes.io/master
replicaCount: 1
affinity: {}
podSecurityPolicy:
  enabled: false

serviceMonitor:
  enabled: false
  #! Install the ServiceMonitor into a different Namespace, as the monitoring stack one (default: the release one)
  namespace:
  #! Assign additional labels according to Prometheus' serviceMonitorSelector matching labels
  labels: {}
  annotations: {}
  matchLabels: {}
  serviceAccount:
    name: capsule
    namespace: capsule-system

