#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels")

apiVersion: v1
kind: Service
metadata:
  name: #@ fullName() + "-webhook-service"
  labels: #@ labels()
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 9443
  selector: #@ selectorLabels()
  sessionAffinity: None
  type: ClusterIP
