#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels")

apiVersion: v1
kind: Secret
metadata:
  labels: #@ labels()
  name: #@ secretCaName()
data:
