#@ load("@ytt:data", "data")
#@ load("config.lib.yml", "name", "fullName", "chart", "labels", "selectorLabels")

#@ if data.values.serviceAccount.create:
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ serviceAccountName()
  labels: #@ labels()
  annotations:
  #@ if data.values.annotations:
    #@  return data.values.serviceMonitor.labels
  #@ end
#@ end
